### ISSUE TITLE
Update API list

### ISSUE THREAD

**Issue by jefferya** [cwrc/tech_documentation#1]
Todo: add missing API's, see conversation below for a list. 

- [x] https://github.com/cwrc/islandora_cwrc_credit_visualization
- [x] https://github.com/Islandora/islandora_oai
- [x] make islandora_rest more noticeable #2 
- [x] highlight solr search in islandora_rest? #2 #3
- [x] likely misses the load/save/lock APIs used by the CWRC-Writer #2 #3
 - [x] see below for more items to check

Hi Jeff, a colleague wants to include mention of CWRC in an overview of cultural heritage APIs. She asks the following
```I am wondering however, whether there is any additional documentation on how to use the API from the outside for a simple search? The current documentation that you have linked to seems to be aimed more at setting up the API for an Islandora installation and using it internally?```
Do we have such documentation and if so can you point me to it or tell me and Mihaela how we might search for it? Thx!

Jeff Antoniuk [08:51]
The API documentation is within each GitHub repo.
I don't know if there is a doc that ties together the pieces.
What document did you link to?
Example GitHub repos off the top of my head
- https://github.com/cwrc/cwrc_islandora_bagit
- islandora_rest
- cwrc_entities
- islandora_cwrc_writer / islandora_cwrc_document / islandora_object_lock (API undocumented to load/save/lock documents)
cwrc/cwrc_islandora_bagit
Provides CWRC customization to the Islandora BagIt integration.
Language
PHP
Last updated
6 months ago
cwrc/cwrc_islandora_bagitJun 5th, 2018Added by GitHub
Also
- workflow
- schema validataion
Some documentation here:
https://github.com/cwrc/tech_documentation#rest-apis
cwrc/tech_documentation
Centralized storage for cwrc technical documentation.
Last updated
5 months ago
cwrc/tech_documentationJul 18th, 2017Added by GitHub

Note: the above is incomplete as it likely misses the load/save/lock APIs used by the CWRC-Writer
There is search API within the islandora_rest, for a link and details see https://github.com/cwrc/tech_documentation#rest-apis

Jeff Antoniuk [09:16]
Also, not mentioned in the tech_documentation is the OAI endpoint (though currently in use https://github.com/Islandora/islandora_oai)
Islandora/islandora_oai
Provides support for an Islandora site to be visible via the Open Archives Initiative Protocol for Metadata Harvesting (OAI-PMH).
Stars
4
Language
PHP
Islandora/islandora_oaiApr 27th, 2012Added by GitHub
